import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import I18nProvider from "@/provider/I18nProvider";
import { SnackBarAppToaster } from "@/hooks/usesnack-bar";

const poppins = localFont({
  src: "../../public/assets/fonts/Poppins-Regular.ttf",
  variable: "--font-poppins",
  weight: "400",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} font-poppins antialiased`}>
        <I18nProvider>{children}</I18nProvider>
        <SnackBarAppToaster />
      </body>
    </html>
  );
}
